mygrep関数追加

diff --git a/zsh/.zprezto/runcoms/zpreztorc b/zsh/.zprezto/runcoms/zpreztorc
--- a/zsh/.zprezto/runcoms/zpreztorc
+++ b/zsh/.zprezto/runcoms/zpreztorc
@@ -12,6 +12,66 @@
 # Set relogin alias
 alias relogin='exec $SHELL -l'
 
+#Set myGrep func
+mygrep() {
+    declare -i argc=0
+    arg=()
+    
+    usage() {
+        echo "Usage: myGrep [-r or -L] [path] [-name FilePatern] [KeyWord]" 1>&2
+    }
+
+    while (( $# > 0 ))
+    do
+        case "$1" in
+            -*)
+                if [[ "$1" =~ name ]]; then
+                    shift
+                    file_patern="-name $1"
+                elif [[ "$1" =~ r ]]; then
+                    grep_method="-r"
+                elif [[ "$1" =~ L ]]; then
+                    grep_method="-L"
+                elif [[ "$1" =~ help ]]; then
+                    usage
+                    return 0
+                fi
+                shift
+                ;;
+            *)
+                ((++argc))
+                arg=("${arg[@]}" "$1")
+                shift
+                ;;
+        esac
+    done
+
+    # 引数の確認
+    if [ "$argc" -lt 2 ]; then
+        echo "Error: few arguments."
+        usage
+        return 0
+    elif [ "$argc" -gt 2 ]; then
+        echo "Error: too many arguments."
+        usage
+        return 0
+    fi
+
+    if [ -z $grep_method ]; then
+        echo "Error: grep method isn't selected."
+        usage
+        return 0
+    fi
+    
+    echo "find ${arg[1]} -type f ${file_patern} | xargs grep ${grep_method} \"${arg[2]}\"\n"
+    find ${arg[1]} -type f ${file_patern} | xargs grep "${grep_method}" "${arg[2]}"
+
+    #変数初期化
+    argc=""
+    arg=""
+    file_patern=""
+}
+
 # Set case-sensitivity for completion, history lookup, etc.
 # zstyle ':prezto:*:*' case-sensitive 'yes'
 
